openapi: 3.0.0
info:
  title: item-api
  version: 1.0.0
# servers:
#   - url: http://orderservice-3556955799:9090
paths:
  /order:
    get:
      tags:
        - default
      summary: get
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      deprecated: false
      security: []
